[tasks.builds]
script = '''
cargo build --release
'''

[tasks.record]
script_runner  = "@shell"
script = '''
./target/release/directory-history record -e=Temp,$Recycle.Bin -t c:// -r ${@}
'''
dependencies = ["builds"]


[tasks.compare]
script_runner  = "@shell"
script = '''
./target/release/directory-history cmp ${@}
'''
dependencies = ["builds"]