[tasks.builds]
script = '''
cargo build --release
'''

[tasks.record]
script_runner  = "@shell"
# cargo make record e.json
#-e=Temp,$Recycle.Bin
script = '''
./target/release/directory-history record  -t e:// -r ${@}
'''
dependencies = ["builds"]


[tasks.compare]
script_runner  = "@shell"
script = '''
./target/release/directory-history cmp ${@}
'''
dependencies = ["builds"]